### ISSUE TITLE
The example doesn't work out of the box

### ISSUE THREAD

**Issue by JimmyRittenborg** [xzyfer/gulp-sass-graph#1]
I've been fiddling around with this module for a couple of hours now, and I simply can't get it to work.

When changing _test-input/include-test.scss_ it works, but when changing the partial it depends on _test-input/includes/_test.scss_ it doesn't (although it lies a bit about it), and a change to _test-output/include-test.css_ never occurs. 

I've also tried using it with gulp-sass (the node-sass > libsass version) which per sass-lang spec correctly ignores processing of _partials out of the box.

Anyway - I throw in a couple of filelog() ( gulp-filelog ) which tells us that the output that gets passed on to sass when saving the partial, is empty. Which isn't the case when saving the main file that imports it.

**In my gulpfile.js:**

``` javascript
gulp.task('watch-sass', function(cb) {
  return watch({glob:options.SRC_DIR + '/**/*.scss', emitOnGlob: true, name: "Sass"})
    .pipe(sassGraph(options.SASS_INCLUDEPATHS))
    .pipe(filelog())
    .pipe(sass({loadPath: options.SASS_INCLUDEPATHS}))
    // .pipe(sass({
    //     includePaths: options.SASS_INCLUDEPATHS,
    //     outputStyle: 'compressed'
    // }))
    .pipe(filelog())
    .pipe(notify('Sass compiled <%= file.relative %>'))
    .pipe(gulp.dest(options.DIST_DIR + '/css'))
    .pipe(livereload());
});
```

**The output:**

```
[gulp] Sass saw _test.scss was changed
processing test-input/includes/_test.scss
[gulp] [15] [/Users/jimmy/Sites/somesite.dev/test-input/includes/_test.scss]
[gulp] [15] [/Users/jimmy/Sites/somesite.dev/test-input/includes/_test.scss]
processing test-input/include-test.scss, which depends on test-input/includes/_test.scss
[gulp] [16] [test-input/include-test.scss] [EMPTY]
[gulp] [16] [test-input/include-test.scss] [EMPTY]
[gulp] _test.scss was reloaded.
... Reload /Users/jimmy/Sites/somesite.dev/test-output/css/includes/_test.scss ...
[gulp] include-test.scss was reloaded.
... Reload /Users/jimmy/Sites/somesite.dev/test-output/css/include-test.scss ...
```

I really wish that I could fix it myself and just send you a PR, but I'm still a noob at all this :/

**Comment by lox** [comment]
Thanks, I'm planning on splitting out this repo into a separate tool command line tool for listing dependencies of a sass file. I'll also put together some tests.
