### ISSUE TITLE
gulp-sass

### ISSUE THREAD

**Issue by sindresorhus** [xzyfer/gulp-sass-graph#3]
Can you contribute back to gulp-sass instead of duplicating efforts?

**Comment by lox** [comment]
I don't have a lot of interest in contributing to gulp-sass, no. Frankly gulp and grunt seem fundamentally broken to me, in that they are a pipeline abstraction of things which are by nature tree-structured. I'm going to delete this repo, I've moved the sass graph parsing over https://github.com/lox/sass-graph.
